### ISSUE TITLE
Can i reimplement `xdotool mousemove 200 100` with node-x11?

### ISSUE THREAD

**Issue by aurium** [sidorares/node-x11#111]
[`xdotool`](http://www.semicomplete.com/projects/xdotool/) is a nice X11 event emitter that can automatize user interaction.

I also would to freely simulate mouse clicks and keypress on X root to affect the pointed/focused window.

How could i do?

**Comment by sidorares** [comment]
yes, you'll need to use xtest extension ( this is what xdotool is using )
see exampe here - https://github.com/sidorares/node-x11/blob/master/examples/smoketest/xtesttest.js#L9-L10

**Comment by sidorares** [comment]
Test.ButtonPress for mouse event - https://github.com/sidorares/node-x11/blob/master/lib/ext/xtest.js#L29-L33

**Comment by sidorares** [comment]
extension docs: http://www.x.org/releases/X11R7.7/doc/xextproto/xtest.html

**Comment by aurium** [comment]
Move mouse is working nicely!

But the `KeyPress` is not that a simple mortal can expect. :-p
You know a reliable node module to translate chars to keycodes?
All that i know is to list `xmodmap -pke`.

**Comment by sidorares** [comment]
https://github.com/substack/node-keysym and https://github.com/sidorares/node-x11/blob/master/examples/tetris.js#L250-L265 ?

**Comment by aurium** [comment]
Thanks @sidorares, i get some time to understand but works nice.
I also did the pull request #112 allowing us to recognize AltGr key.
