### ISSUE TITLE
Get Window Properties using X.getProperty - unable to decipher the output

### ISSUE THREAD

**Issue by bhavyaw** [sidorares/node-x11#126]
First of all thanks for writing such an amazing utility. I am hoping you could help me with a slight problem I am facing. 

My end objective is to track the application usage i.e how much time a user spends on a particular application for eg : chrome browser, notepad ++ editor or any other application for that matter.

For this we need to detect the active window change ( essentially active process changes ). Gladly I came across the code snippet posted by you on SO ( [link](http://stackoverflow.com/questions/19840459/linux-get-notification-on-focused-gui-window-change) ) and was able to detect the active window changes. 

However, we need to **extract the process ID ( PID )** from the information we have in hand. I tried using **`X.getProperty`** method as mentioned by you in the post and **outputs an array of length 4**. **How can i retrieve process id from this output**. There isn't much documentation in regard on the github page or elsewhere.

**Here the output :** 
![screenshot from 2016-05-23 18 09 10](https://cloud.githubusercontent.com/assets/6906721/15471375/3d7050a4-2113-11e6-8cfb-28ba698ac221.png)

**Here the code I am using :** 

```
var x11 = require('x11');

x11.createClient(function(err, display) {
  var X = display.client;

  var win = display.screen[0].root;
  X.ChangeWindowAttributes(win, { eventMask: x11.eventMask.PropertyChange });

    X.on('event', function(ev) {
        if(ev.name == 'PropertyNotify') {
          X.GetAtomName(ev.atom, function(err, name) {
            if (name == '_NET_ACTIVE_WINDOW') {
                console.log('Active window changed',X,window,ev.atom);
                X.GetProperty(0,win,ev.atom,X.atoms.WINDOW,0,4, function(err, prop) {
                    if (!err) {
                      console.log(prop.data); 
                         // outputs : [130, 0, 128, 4]
                         // what's this information in this array ? 
                         // Can we use this array somehow to get the process id of the active window?
                    }
                });
            }
          });
        }
    }); // ending on event listener


});

```

I'll be much grateful if you could provide any help in this regard. Thanks in advance. :)

**Comment by sidorares** [comment]
pid should be stored in `_NET_WM_PID ` property  - see  https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm140200472565744

also have a look at https://github.com/santigimeno/node-ewmh/blob/10d9e4cfebec8230c0a150a3b84a5e5f620d011c/lib/ewmh.js#L71 ( it's a setter, but format is similar )

**Comment by sidorares** [comment]
and to answer your question - "outputs an array of length 4" - these are 4 bytes of `CARDINAL/32` type ( unsigned 32 bit int ). In node you can do something like `Buffer([1, 2, 3, 4]).readUInt32LE(0)`. There is also browser-y way: `new Float32Array((new Uint8Array([i1,i2,i3,i4])).buffer)[0];`  - see 
http://www.html5rocks.com/en/tutorials/webgl/typed_arrays/
and http://stackoverflow.com/questions/26152024/pack-4-8-bit-unsigned-integer-to-a-32-bit-float

**Comment by santigimeno** [comment]
This may also help you to get the  `_NET_WM_PID` property: https://github.com/santigimeno/node-x11-prop. The example is for `WM_CLASS` but you get the idea.

**Comment by sidorares** [comment]
yes, even better

I think https://github.com/santigimeno/node-x11-prop/blob/master/examples/get_set_prop.js#L19
replaced with `get_property(X, wid, '_NET_WM_PID', 'CARDINAL, function(err, data) { //...` should work

**Comment by bhavyaw** [comment]
Thanks a ton for your suggestion. I tried the suggestions mentioned above except ewmh ( extended window manager hints ), I am sorry but I am still not getting the PID.

Here's what i tried so far:

1.  

**Code:**

```
var X = display.client;
    var win = display.screen[0].root;
    var wid = X.AllocID();

    X.ChangeWindowAttributes(win, { eventMask: x11.eventMask.PropertyChange });
    X.on('event', function(ev) {
        if(ev.name == 'PropertyNotify') {
          X.GetAtomName(ev.atom, function(err, name) {
            if (name == '_NET_ACTIVE_WINDOW') {
              get_property(X, wid, '_NET_WM_PID', 'CARDINAL', function(err, data) {
                console.log('===>  ',data);
              });
            }
          });
        }
    }); // ending on event listener
```

**Output:**

![screenshot from 2016-05-23 20 46 03](https://cloud.githubusercontent.com/assets/6906721/15475373/6679a018-2127-11e6-95ac-10549cb584f0.png)



2.  In the above example I thought wid shouldn't be `X.AllocID();` but should be ev.wid i.e wid which we get from the event obj. So, i tried this:

**Code :**
```
  X.on('event', function(ev) {
        if(ev.name == 'PropertyNotify') {
          X.GetAtomName(ev.atom, function(err, name) {
            if (name == '_NET_ACTIVE_WINDOW') {
              get_property(X, ev.wid, '_NET_WM_PID', 'CARDINAL', function(err, data) {
                console.log('Inside get_property function, Data captured is: ',data);
              });
            }
          });
        }
    }); // ending on event listener
```

**Output :**


![screenshot from 2016-05-23 20 44 28](https://cloud.githubusercontent.com/assets/6906721/15475338/2cce4094-2127-11e6-94a8-4a731ea901fb.png)


3. So, when the second method didn't I explored a little more I found out that `get_property` internally uses `X.GetProperty`. From the source of X.GetProperty here https://github.com/sidorares/node-x11/blob/master/autogen/proto/xproto.xml#L2083, i tried to understand what argument this function accepts. So, from there i came to know the X.GetProperty actually accepts type atom and not the property name to which atom corresponds. So, then i tried this:

**Code:**

    X.on('event', function(ev) {
        if(ev.name == 'PropertyNotify') {
          X.GetAtomName(ev.atom, function(err, name) {
            if (name == '_NET_ACTIVE_WINDOW') {
              X.InternAtom(false,'_NET_WM_PID',function(err,atom){
                get_property(X,ev.wid,atom , 'CARDINAL', function(err, data) {
                  console.log('Inside get_property function, Data captured is: ',data);
                });
              });
            }
          });
        }
    }); // ending on event listener


**Output :**

![screenshot from 2016-05-23 20 57 31](https://cloud.githubusercontent.com/assets/6906721/15475706/03c0db74-2129-11e6-8b08-8fd7f00eb9a8.png)


I will keep trying more stuff as i really need to get this working but, it will be much easier for me if you guys help me out a little bit more on this one. Can you please tell me where I am going wrong or can you please try and confirm the suggestions you gave me.

Environment I am working on:

OS : Ubuntu 14.04 LTS
Platform : Node-webkit ( 14.3 )

In case this is of any help.


Thanks Again.

**Comment by bhavyaw** [comment]
Thanks a ton for your suggestions. I tried all the suggestions except ewmh ( extended window manager hints ) but still in vain.

This is what i tried so far:

**1.** 

**Code :**
  ```
var X = display.client;
  var win = display.screen[0].root;
  var wid = X.AllocID();
  X.ChangeWindowAttributes(win, { eventMask: x11.eventMask.PropertyChange });

  X.on('event', function(ev) {
      if(ev.name == 'PropertyNotify') {
        X.GetAtomName(ev.atom, function(err, name) {
          if (name == '_NET_ACTIVE_WINDOW') {
            get_property(X, wid, '_NET_WM_PID', 'CARDINAL', function(err, data) {
              console.log('Inside get_property function, Data captured is: ',data);
            });
          }
        });
      }
  }); // ending on event listener
```

**Ouput**:

![screenshot from 2016-05-23 20 34 30](https://cloud.githubusercontent.com/assets/6906721/15476915/9b5f022a-212f-11e6-9ca5-b3fffbb1805d.png)



**2.** 
Then, i thought that we should shouldn't be using `X.AllocID();` as window but instead use `ev.wid` from the event obj as this might actually correspond to the window which is actually changing.

**Code :**

```
  X.on('event', function(ev) {
      if(ev.name == 'PropertyNotify') {
        X.GetAtomName(ev.atom, function(err, name) {
          if (name == '_NET_ACTIVE_WINDOW') {
            get_property(X, ev.wid, '_NET_WM_PID', 'CARDINAL', function(err, data) {
              console.log('Inside get_property function, Data captured is: ',data);
            });
          }
        });
      }
  }); // ending on event listener
```

**Ouput:**
![screenshot from 2016-05-23 20 44 28](https://cloud.githubusercontent.com/assets/6906721/15476983/fa4e9958-212f-11e6-864c-000eafeab055.png)
![screenshot from 2016-05-23 20 57 31](https://cloud.githubusercontent.com/assets/6906721/15476986/01505dcc-2130-11e6-878e-fa41045a3760.png)




**3.** 
Next, i looked into `get_property `method and came to it uses `X.GetProperty `internally from [here](https://github.com/santigimeno/node-x11-prop/blob/master/lib/get_prop.js#L57). I tried to understand the X.GetProperty implementation and and the arguments it accepts [link](https://github.com/sidorares/node-x11/blob/master/autogen/proto/xproto.xml#L2083). I think this function actually accepts atom type instead of string representation of the property i.e `_NET_WM_PID`. So, i first i tried to extract the atom corresponding to this property and using this in get_property function.


**Code** :
  ```
X.on('event', function(ev) {
      if(ev.name == 'PropertyNotify') {
        X.GetAtomName(ev.atom, function(err, name) {
          if (name == '_NET_ACTIVE_WINDOW') {
            X.InternAtom(false, '_NET_WM_PID', function(false,atom){
              get_property(X, ev.wid,atom, 'CARDINAL', function(err, data) {
                console.log('Inside get_property function, Data captured is: ',data);
              });
            });
          }
        });
      }
  }); // ending on event listener
```

**Ouput:**

![screenshot from 2016-05-23 20 57 31](https://cloud.githubusercontent.com/assets/6906721/15476992/08b40442-2130-11e6-92c6-2ec47844333e.png)

but still it didn't work.


I'll continue to keep working on this as I really need to get this working but I will a lot easier for me if you could help a little bit with this one. Can you please let me know where I might be going wrong or please confirm the suggestion you gave me earlier.


My working environment :

**Comment by sidorares** [comment]
This works for me:

```js
x11.createClient(function(err, display) {
  var X = display.client;
  X.InternAtom(false, '_NET_WM_PID', function(err, pidAtom ) {
    X.ChangeWindowAttributes(display.screen[0].root, { eventMask: x11.eventMask.PropertyChange });
    X.on('event', function(ev) {
      if(ev.name == 'PropertyNotify') {
        X.GetAtomName(ev.atom, function(err, name) {
          if (name == '_NET_ACTIVE_WINDOW') {
            X.GetProperty(0, display.screen[0].root, ev.atom, X.atoms.WINDOW, 0, 4, function(err, prop) {
              var active = prop.data.readUInt32LE(0);
              X.GetProperty(0, active, pidAtom, X.atoms.CARDINAL, 0, 4, function(err, prop) {
                console.log('PID:', prop.data.readUInt32LE(0));
              });
            });
          }
        });
      }
    });
  });
});
```

**Comment by bhavyaw** [comment]
This works perfectly.
I can't thank you enough. Much Appreciated.

**Comment by santigimeno** [comment]
Just for completion. The same code using `x11-prop`:

```
var x11 = require('x11');
var x11prop = require('x11-prop');
var get_property = x11prop.get_property;

x11.createClient(function(err, display) {
    if (err) {
        throw err;
    }

    var X = display.client;
    var root = display.screen[0].root;

    /* Create a new window */
    X.ChangeWindowAttributes(root, { eventMask: x11.eventMask.PropertyChange });
    X.on('event', function(ev) {
        if(ev.name === 'PropertyNotify') {
            X.GetAtomName(ev.atom, function(err, name) {
                if (name === '_NET_ACTIVE_WINDOW') {
                    get_property(X, ev.wid, ev.atom, function(err, data) {
                        console.log('_NET_ACTIVE_WINDOW: ' + data);
                        get_property(X, data[0], '_NET_WM_PID', function(err, data) {
                            console.log('_NET_WM_PID: ' + data);
                        });
                    });
                }
            });
        }
    });
});

```

**Comment by GideonWolfe** [comment]
For anyone coming across this in 2020, the following worked for me:

```javascript
var x11 = require('x11');
x11.createClient(function(err, display) {
  var X = display.client;
  X.ChangeWindowAttributes(display.screen[0].root, { eventMask: x11.eventMask.PropertyChange });
  X.on('event', function(ev) {
    console.log(ev)
    if(ev.name == 'PropertyNotify') {
      X.GetAtomName(ev.atom, function(err, name) {
        if (name == '_NET_ACTIVE_WINDOW') {
          X.GetProperty(0, ev.wid, ev.atom, X.atoms.WINDOW, 0, 4, function(err, prop) {
            console.log('New active window:' + prop.data.readUInt32LE(0));
          });
        }
      });
    }
  });
});
```

The code using `get_property` threw errors sending me towards [this](https://github.com/serialport/node-serialport/issues/2051) rabbit hole, but the `X.GetProperty` was throwing `Bad Window` error. 

Changing `ev.window` to `ev.wid` seems to work because there is actually a `ev.wid` value in the returned data.
