### ISSUE TITLE
How get window title and type?

### ISSUE THREAD

**Issue by AdrianoPatrizio** [sidorares/node-x11#139]
I need to get window title and type for my project, how get these?

**Comment by sidorares** [comment]
hi @AdrianoPatrizio did you manage to find the answer yourself?

**Comment by AdrianoPatrizio** [comment]
Yes, I'm sorry, I have find the answer in ./esamples/simple/getprop.js directory of git.

**Comment by sidorares** [comment]
great. Feel free to open new issues if you have more questions

Also there is https://github.com/santigimeno/node-ewmh with some useful helpers
