### ISSUE TITLE
X Extension Dependencies

### ISSUE THREAD

**Issue by ConsciousCode** [sidorares/node-x11#146]
Would it be possible to mention in the README the extra dependencies required to compile node-x11? It took extra effort on my end to get it to compile, and I don't think that meshes well with the ethos of npm.

I needed to install Xfixes (libxfixes-dev) and Xtest (libxtst-dev), but there could be other dependencies I'm unaware of.

**Comment by ConsciousCode** [comment]
Ah, pardon me, I installed node-x11 instead of x11, so this doesn't apply.

**Comment by sidorares** [comment]
nah, for a long time this module even had zero external npm dependencies ( now it does have only one - `os-homedir`  which we might drop since it's only for node pre v4 )

what are you trying to build with x11 @ConsciousCode ?

**Comment by ConsciousCode** [comment]
I was looking into the possibility of making a lightweight WM for my own personal use. I've always liked the idea of having a fully customizable WM that could be updated on the fly with Javascript.

**Comment by sidorares** [comment]
I linked small number of wms created with this lib in the readme, that was one of my goals as well ( to create WM I like ) but still not there. Ideally I'd like to see something like i3 but more advanced and customizable, maybe similar to https://palantir.github.io/react-mosaic/ or atom editor tabs/panes drag and drop

**Comment by anko** [comment]
Sounds like many people share the idea of a JavaScript WM! My hack is [basedwm](anko/basedwm) and [hudkit](anko/hudkit). If you need any help, I'll lurk in the [node-x11 gitter](https://gitter.im/sidorares/node-x11).
