### ISSUE TITLE
Questions regarding this lib

### ISSUE THREAD

**Issue by elderapo** [sidorares/node-x11#154]
Hello!

When I was checking out examples in this repo I came up with an idea of making software similar to [LightShot](https://app.prntscr.com/pl/) but for Linux.

In [this](https://github.com/sidorares/node-x11/blob/master/examples/screenshot.js#L74) example we can see how to render current "screen dump" to other window. If I am not mistaken the first argument passed to ```X.getImage``` is supposed to be ```format``` which happens to be set to 2 in given example. I didn't really know what it meant so I searched this repo and found [this](https://github.com/sidorares/node-x11/blob/18cbbdf6ee07091d29d064406104263dcce87aee/lib/corereqs.js#L848) line. Unfortunately if I set format to 0 (bitmap according to previous link) in ```X.getImage``` I get this error:
```
{ Error: Bad param value
    at ReadFixedRequest.callback (/home/elderapo/nodejs/node-x11/lib/xcore.js:465:29)
    at ReadFixedRequest.execute (/home/elderapo/nodejs/node-x11/lib/unpackstream.js:41:10)
    at UnpackStream.resume (/home/elderapo/nodejs/node-x11/lib/unpackstream.js:165:30)
    at UnpackStream.write (/home/elderapo/nodejs/node-x11/lib/unpackstream.js:102:10)
    at Socket.<anonymous> (/home/elderapo/nodejs/node-x11/lib/xcore.js:88:21)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
  error: 2,
  seq: 7,
  message: 'Bad param value',
  badParam: 0,
  minorOpcode: 0,
  majorOpcode: 73 }
```
I guess this error means that 0 (bitmap) is incorrect value and that if I want to get bitmap I should convert `ZPixmap` to bitmap. If so any tips how I can achive that?

Also I was wondering if it's possible to get color of the pixel at given coordinates in x window. I found some c++ snippets using ```XGetImage``` and ```XGetPixel``` to achieve that but I couldn't find anything about ```GetPixel``` in this repo.

**Comment by polpo** [comment]
In X11 terms, a bitmap is an image represented by 1 bit per pixel, which is probably not what you want. The ZPixmap captured by `X.GetImage` is in the format BGRA, so it should be pretty simple to loop through `image.data` and convert to RGBA or RGB, ready for saving as a PNG, putting into a `canvas` element, etc.

**Comment by sidorares** [comment]
> Also I was wondering if it's possible to get color of the pixel at given coordinates in x window. I found some c++ snippets using XGetImage and XGetPixel to achieve that but I couldn't find anything about GetPixel in this repo.

This library tries to implement x11 protocol, and there is no 'GetPixel' request in the protocol ( though you can get 1x1 rectangle with XGetImage. When you do XGetPixel with xlib it probably grabs some area using `GetImage` request, stores it locally and then retrieves pixel value from that data

**Comment by elderapo** [comment]
Thanks for the answers!

I managed to save screenshot to file using [following code](https://gist.github.com/elderapo/39a5864078d08dbef4395c2aa1e225e7). It will suit "LightShot clone" needs.

I also noticed that `X.GetImage` is kind of slow. It takes ~70 ms to get 1920x1080 image (`X.GetImage` takes that much - not conversion from BGRA to RGBA). Is there anything I can do to easly improve `X.GetImage` performance?

**Comment by sidorares** [comment]
You can try to use MIT-SHM extension. The idea is that if server and client share same memory you can avoid copying large amount of data over network ( 1920x1080x32bit = 6 MBytes, 70 ms  not that bad actoally for this amount )

**Comment by sidorares** [comment]
Can't remember what's the status of mit-shm extension here I did some research a while ago but as far as I can remember not finished implementation. Would be good to add it
 
https://www.npmjs.com/package/nodeshm
https://www.x.org/releases/X11R7.7/doc/xextproto/shm.txt

**Comment by Heath123** [comment]
> You can try to use MIT-SHM extension. The idea is that if server and client share same memory you can avoid copying large amount of data over network ( 1920x1080x32bit = 6 MBytes, 70 ms not that bad actually for this amount )

But in a C program `XGetImage` takes about 7ms

**Comment by sidorares** [comment]
This client is not perfect and adds some overhead. I'm thinking about a complete rewrite to make use modern stream and Buffer helpers

**Comment by Heath123** [comment]
Never mind, it's actually 0.023ms. Still a big improvement though
