### ISSUE TITLE
Small unpacking typos in the handshake 

### ISSUE THREAD

**Issue by chrisdone** [sidorares/node-x11#168]
In [handshake.js L85](https://github.com/sidorares/node-x11/blob/ce51cefdad251ccc4fa82cb34e3acf4a618d8e39/lib/handshake.js#L85..L89) there is this benign issue:

```javascript
bl.unpackTo( scr,
[
// [snip]
   'S max_installed_maps',
   'L root_visual',
   'C root_depth',  
    // ^^^^ this should not be here: the next thing after root_visual should be backing_stores
   'C backing_stores',
   'C root_depth', /// <-- root depth is duplicated here, and no save_unders is considered
   'C num_depths'
],
function () {
    var depths = {};
```
 
From the X11 protocol spec, it should be:

<img width="814" alt="screenshot 2018-04-08 19 43 10" src="https://user-images.githubusercontent.com/11019/38471148-214ad016-3b65-11e8-82fa-e05ea42c3c0a.png">

So:

* your first `root_depth` should be dropped ✂️  
* your second `root_depth` is fine 👍 
* and it should be followed by `save_unders` 🆕 

I'm currently implementing a teeny X11 server and I'm using your client to test it and insert debug statements. I was comparing your "unpack" to my "pack" to see if they line up and just happened to notice this discrepancy! 😄 

I think it doesn't actually cause a bug or anything because the values coincidentally line up or aren't used. I'll let you know if I find anything else.

**Comment by sidorares** [comment]
Hi! Thanks for this @chrisdone !
Can you submit PR so the change goes under your name?
