### ISSUE TITLE
Can't get WM_STATE

### ISSUE THREAD

**Issue by SpaceboyRoss01** [sidorares/node-x11#174]
I can't get the `WM_STATE` property https://tronche.com/gui/x/xlib/ICC/.
```
				this.panel.app.getXClient().InternAtom(false,"WM_STATE",(err,WM_STATE) => {
					if(err) throw err;
					this.panel.app.getXClient().GetProperty(0,wID,WM_STATE,WM_STATE,0,32,(err,data) => {
						if(err) throw err;
						console.log(data);
						this.windowCount++;
					});
				});
```

**Comment by sidorares** [comment]
`GetProperty` third parameter is property type, see https://github.com/sidorares/node-x11/blob/174cff9a9cdfff527ff03f799fd1e07c017190b0/lib/corereqs.js#L484

https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html#requests:GetProperty

I think you can pass 0 for `AnyPropertyType` , not sure what exactly type stored for WM_STATE, probably array of cardinals

**Comment by santigimeno** [comment]
`WM_STATE` is not only a property but also a type. [x11-prop](https://github.com/santigimeno/node-x11-prop#get-property) should help you with that. Something like this should work:

```js
x11prop.get_property(X, did, 'WM_STATE', (err, data) => {
  if (!err) {
    console.log('WM_STATE: ' + data);
  }
});
```

**Comment by SpaceboyRoss01** [comment]
Ok, got it to work. Now I just need to figure out which windows are visible/mapped.
