### ISSUE TITLE
Add XSetWMNormalHints, XGetWMNormalHints, XSetWMSizeHints, and XGetWMSizeHints

### ISSUE THREAD

**Issue by SpaceboyRoss01** [sidorares/node-x11#177]
Here's a list of useful functions that should be added:
* [XSetWMNormalHints](https://tronche.com/gui/x/icccm/sec-4.html#WM_NORMAL_HINTS)
* [XGetWMNormalHints](https://tronche.com/gui/x/icccm/sec-4.html#WM_NORMAL_HINTS)
* [XSetWMSizeHints](https://tronche.com/gui/x/icccm/sec-4.html#WM_SIZE_HINTS)
* [XGetWMSizeHints](https://tronche.com/gui/x/icccm/sec-4.html#WM_SIZE_HINTS)

**Comment by SpaceboyRoss01** [comment]
Well, I think they are a part of the core protocol.

**Comment by sidorares** [comment]
No, they are part of xlib but not core protocol. Basically just simple wrappers on top of SetProperty request

https://github.com/mirror/libX11/blob/b676e62377483df77bcb6472d26b24f901323fa9/src/SetNrmHint.c#L114

**Comment by SpaceboyRoss01** [comment]
I think I'll create a package called node-xlib so we can have xlib functions.

**Comment by SpaceboyRoss01** [comment]
Closed since [node-xlib](https://github.com/Ross-Technologies/node-xlib) does this now.
