### ISSUE TITLE
XGetWMHints

### ISSUE THREAD

**Issue by riquenunes** [sidorares/node-x11#191]
Is it just me or the lib doesn't have XGetWMHints available? Is there an alternative way to read WM_HINTS without it?

**Comment by RossComputerGuy** [comment]
It doesn't have `XGetWMHints` and I don't think it will

**Comment by sidorares** [comment]
@riquenunes  this library only provides low level X11 protocol serialisation/deserealisation. You can fill feature request to add `WM_HINTS` to https://github.com/santigimeno/node-ewmh (or manually read them, you use `InternAtom` /  `GetProperty` / `ChangeProperty` to get WM_HINTS buffer and follow spec https://tronche.com/gui/x/icccm/sec-4.html to decode it values out

**Comment by sidorares** [comment]
related - https://github.com/sidorares/ntk/issues/19
