### ISSUE TITLE
Can't register ButtonPress event for windows

### ISSUE THREAD

**Issue by dkirchhof** [sidorares/node-x11#196]
Hello,

just for fun i'm trying to implement a tiny windowmanager with this library.
After a window sends a map request, i call `x.MapWindow(windowId)` and place the window somewhere on the screen.
Now i want to focus windows by clicking on them. So i set the `eventMask` of the new window to receive a button press event:

```ts
x.ChangeWindowAttributes(windowId, {
    eventMask: eventMask.ButtonPress,
});
```

Unfortunately i get a bad access error:

```ts
{
  error: 10,
  seq: 107,
  badParam: 16777223,
  minorOpcode: 0,
  majorOpcode: 2
}
```

If i change the `ButtonPress` to `ButtonRelease` or `KeyPress`, the error doesn't occur anymore. (btw: The button release event wouldn't be triggered, the key press event will be triggered as expected).

What the heck is going on there? Can someone help me?

---

If this approach is totally wrong, please tell me. I tried to handle button press events via `x.GrabButton`, but had also some issues... but this is another story :weary:.

**Comment by sidorares** [comment]
Have a look at answers here - https://stackoverflow.com/questions/16977872/xselectinput-is-not-working-for-buttonpressevents-how-to-do-it Unlike most other event masks only one client is allowed to set ButtonPress

**Comment by dkirchhof** [comment]
Sorry, but i don't geht the right solution. Now i know that i can't use the first approach but as i mentioned before i have also problems with the grabButton function:.  
Well, i use grabButton for all of my managed windows. If one window gets the focus, i ungrab the button, so i can click on elements inside it (otherwise the button press events wouldn't be propagated down).   
I'm okay with this solution, but now i have to focus a window first and then i can click on elements inside of it. That means i have to click twice on unfocused windows to open a menu for example.

I studied some others wms. So i'm missing something. Maybe it has something to do with `XSelectInput` (which doesn't exist in this bindings?) or with `XAllowEvents`?! 🤷‍♂️

**Comment by sidorares** [comment]
XSelectInput performs ChangeWindowAttributes request under the hood - https://github.com/mirror/libX11/blob/caa71668af7fd3ebdd56353c8f0ab90824773969/src/SelInput.c#L44

**Comment by dkirchhof** [comment]
Thanks for your quick replies. I got it.
According to this [thread](https://stackoverflow.com/questions/46288251/capture-button-events-in-xlib-then-passing-the-event-to-the-client), respectively this [issue](https://github.com/c00kiemon5ter/monsterwm/issues/12#issuecomment-15343347), i slightly improved the second approach. So i changed the `pointerMode` to sync and call `AllowEvents` with `ReplayPointer`-mode in the event handler.

```ts
const wid = root;
const reportWindow = 0; // don't report
const pointerMode = 0; // sync
const keybMode = 1; // async
const confineTo = 0; // none
const evMask = eventMask.ButtonPress;
const cursor = 0; // none
const button = 1;
const modifiers = 1 << 15 // any;

// wid, ownerEvents, mask, pointerMode, keybMode, confineTo, cursor, button, modifiers
x.GrabButton(wid, reportWindow, pointerMode, keybMode, confineTo, evMask, cursor, button, modifiers);
```

```ts
const onButtonPressed = e => {
    // pass the event down to the client
    x.AllowEvents(2, e.time); // 2 = replayPointer

    // use child instead of wid, as the wid points to the root window
    setFocus(e.child);
};
```
