### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by Industrial** [sidorares/node-x11#208]
Hi. Could you add TypeScript types? That would be much appreciated.

gr,

Tom

**Comment by sidorares** [comment]
Hi Tom,
would be good to have typings. Not sure if I have capacity to do that anytime soon, and also would prefer automatic / semi-automatic solution ( parce protocol xml description and output types, maybe parse JS source to augment that as well, Might be partially based on #3 )

Happy to review and try to help if somebody can start start this work
