### ISSUE TITLE
How can I listen to the root events?

### ISSUE THREAD

**Issue by arnm** [sidorares/node-x11#69]
I see the examples show how to listen to a specific window's events but is there a way to listen to the root window's events?

I need to manage global events.

**Comment by aurium** [comment]
I want to track the mouse.
I'm using Gnome, but i believe we can get a generic and simple way.

Why events don't bubble? Or... `node-x11` can't force composite wms to bubble events to be listen at root?

**Comment by sidorares** [comment]
can you see them with [xev(1)](http://linux.die.net/man/1/xev) ?
node-x11 only can see what network protocol allows. If events ton't reach root window you won't see them. Does it work for you without wm? (or without composite manager?)

**Comment by aurium** [comment]
I could not find how to get this information with `xev`, but i can do with `xdotool getmouselocation`.
So, what dark magic is xdotool using? :-)

**Comment by polpo** [comment]
Looks like all xdotool does is use XQueryPointer: https://github.com/jordansissel/xdotool/blob/f5309ecea01463b3bddb4964978631cd201fb7c6/xdo.c#L866

**Comment by aurium** [comment]
Nice... https://tronche.com/gui/x/xlib/window-information/XQueryPointer.html I believe that is it. :-)
