### ISSUE TITLE
grab keyboard doesn't take effect, need some demo.

### ISSUE THREAD

**Issue by yilang2007lw** [sidorares/node-x11#90]
I want to write a screen locker program thats needs grab keyboard to inhibit other applications.
Below is my node js code, the problem is when press Alt + Tab, still can switch to other app.

//start of js code

var x11 = require('../../lib');
x11.createClient(function(err, display) {
    var X = display.client;
    var wid = X.AllocID();
    X.CreateWindow(wid, display.screen[0].root, -9, -9, 1, 1);
    X.ChangeWindowAttributes(wid, { eventMask: x11.eventMask.ResizeRedirect|x11.eventMask.KeyPress|x11.eventMask.KeyRelease|x11.eventMask.StructureNotify|x11.eventMask.SubstructureNotify});
    X.LowerWindow(wid);
    X.MapWindow(wid);
    //X.GrabPointer(wid, false, x11.eventMask.PointerMotion, 1, 1, wid, 0, Date.now());
    X.on('event', function(ev) {
        if (ev.type === 19) {
            console.log("------------finish map-------------------");
            X.GrabKeyboard(wid, false, new Date(), 1, 1);
            X.LowerWindow(wid);
        } else {
            console.log(ev.name);
        }
        if (ev.type == 2) {
            if (ev.keycode == 36) {
                X.terminate(); 
            } else {
                console.log(ev.keycode);
            }
        }
        if (ev.type == 18) {
            console.log("------------event unmap----------------");
        }
    });

    X.on('error', function(error) {
        console.log("-----------------error-------------------");
        console.log(error);
    });
});
//end of js code

But the coordiante C code works well, then how should  I modify my js code, thanks for any reply.

Below is the c code:

#include <X11/Xlib.h>
#include <X11/keysym.h>
#include <stdio.h>

int main()
{
    Display *display;
    Window   window, rootwindow;
    XEvent   event;
    KeySym   escape;

    display = XOpenDisplay(NULL);
    rootwindow = DefaultRootWindow(display);
    window = XCreateWindow(display, rootwindow,
                           -99, -99, 1, 1, /* x, y, width, height */
                           0, 0, InputOnly, /* border, depth, class */
                           CopyFromParent, /* visual */
                           0, NULL); /* valuemask and attributes */

    XSelectInput(display, window, StructureNotifyMask | SubstructureRedirectMask | ResizeRedirectMask | KeyPressMask | KeyReleaseMask);
    XLowerWindow(display, window);
    XMapWindow(display, window);

    do {
        printf("----------------------event is not map------------------\n");
        XNextEvent(display, &event);
    } while (event.type != MapNotify);

    printf("----------------------now finish map------------------\n");
    XGrabKeyboard(display, window, False, GrabModeAsync, GrabModeAsync, CurrentTime);
    XLowerWindow(display, window);

    escape = XKeysymToKeycode(display, XK_Escape);
    printf("\nPress ESC to exit.\n\n");
    fflush(stdout);

    while (1) {

        XNextEvent(display, &event);

        if (event.type == KeyPress) {
            printf("KeyPress: keycode %u state %u\n", event.xkey.keycode, event.xkey.state);
            fflush(stdout);

        } else
        if (event.type == KeyRelease) {

            printf("KeyRelease: keycode %u state %u\n", event.xkey.keycode, event.xkey.state);
            fflush(stdout);

            if (event.xkey.keycode == escape)
                break;
        } else
        if (event.type == UnmapNotify) {
            printf("---------unmap----------\n");
            fflush(stdout);

            XUngrabKeyboard(display, CurrentTime);
            XDestroyWindow(display, window);
            XCloseDisplay(display);

            display = XOpenDisplay(NULL);
            rootwindow = DefaultRootWindow(display);
            window = XCreateWindow(display, rootwindow,
                                   -99, -99, 1, 1, /* x, y, width, height */
                                   0, 0, InputOnly, /* border, depth, class */
                                   CopyFromParent, /* visual */
                                   0, NULL); /* valuemask and attributes */

            XSelectInput(display, window, StructureNotifyMask | SubstructureRedirectMask | ResizeRedirectMask | KeyPressMask | KeyReleaseMask);
            XLowerWindow(display, window);
            XMapWindow(display, window);

            do {
                XNextEvent(display, &event);
            } while (event.type != MapNotify);

            XGrabKeyboard(display, window, False, GrabModeAsync, GrabModeAsync, CurrentTime);
            XLowerWindow(display, window);

            escape = XKeysymToKeycode(display, XK_Escape);

        } else {

            printf("Event type %d\n", event.type);
            fflush(stdout);
        }
    }

    XUngrabKeyboard(display, CurrentTime);

    XDestroyWindow(display, window);
    XCloseDisplay(display);
    return 0;
}

**Comment by santigimeno** [comment]
@yilang2007lw Calling GrabKeyboard with `time = 0` instead of `Date.now()` should do it. `0` means ' CurrentTime`

**Comment by yilang2007lw** [comment]
It worked, thanks very much.

**Comment by santigimeno** [comment]
np
