### ISSUE TITLE
createClient should fall back to TCP if Unix socket does not exist

### ISSUE THREAD

**Issue by polpo** [sidorares/node-x11#94]
Xlib and XCB fall back to using TCP on localhost if the Unix socket does not exist. node-x11 should do the same. 

We've run into a few instances with users whose /tmp/.X11-unix/X* socket file has been deleted out from under them, but their X session appears to continue to work due to Xlib and XCB's falling back.

**Comment by polpo** [comment]
I'm willing to submit a PR to fix this, but it seems tricky unless I resort to testing the existence of the socketPath with `fs.exists()` or `fs.access()`. I'm a little hesistant to do that because of the relatively infinitesimal risk of the file being deleted between the test and the connect.

If I set an error handler on `stream` ENOENT and replace it with a new `stream`, the XClient has already been created and returned to the caller of `createClient()`.

So, thoughts on just using `fs.exists()` or `fs.access()`?

**Comment by santigimeno** [comment]
I would prefer not using the `fs` methods.
I would just wait for the `ENOENT`error To accomplish this we could split the `XClient` constructor functionality into 2 separate functions:
- The constructor would basically initialize the class attributes and instantiate the `EventEmitter`.
- An `init` method to be called on the `connect` callback, that would really initialize the object: handle the connection, start handshake, etc. This way you could attach the `stream` once you know the connection has been established.

I'm not sure, but I think it could work. What do you think?

**Comment by polpo** [comment]
That seems doable. I'll give it a try.

**Comment by sidorares** [comment]
Yes, seems doable - in error handler see which state we are in, if not connected + unix socket and error is ENOENT than try again using tcp:6000+display ( and if that fails, return callback with error )

Also I think we have difference in behaviour with xlib/xcb when DISPLAY not set at all - we assume it's `:0` in that case. Not sure if that is correct ( or what are possible implications of doing so )

**Comment by polpo** [comment]
Another difference: [`//TODO check if it's consistent with xlib (DISPLAY=127.0.0.1:0 -> local unix socket or port 6000?`](https://github.com/sidorares/node-x11/blob/3e3f1805a2c2a58942a48654e8bc84be0a2b57d8/lib/xcore.js#L584)

I checked and both Xlib/xtrans and XCB connect via TCP if `DISPLAY=127.0.0.1:0`.
