### ISSUE TITLE
GetProperty logs errors

### ISSUE THREAD

**Issue by dizzib** [sidorares/node-x11#96]
Is there any way to prevent it logging on error:

    error { [Error: Bad window]
      error: 3,
      seq: 28,
      message: 'Bad window',
      badParam: 12585040,
      minorOpcode: 0,
      majorOpcode: 20 }

v1.0.3
Thanks!

**Comment by santigimeno** [comment]
@dizzib sample code?

**Comment by dizzib** [comment]
Sorry, my mistake! Some trace code was lurking in my X error handler.
