### ISSUE TITLE
XReadBitmapFile for color images

### ISSUE THREAD

**Issue by klepthys** [sidorares/node-x11#99]
I've implemented a small module to load Xpixmap files in memory and display them using the x11 module, similar to the X11 [XReadBitmapFile](https://tronche.com/gui/x/xlib/utilities/XReadBitmapFile.html) function.

Let me know if you want to have it copied in your use cases or if you want to work with me on an implementation of this function in node-x11.

link to the module : https://www.npmjs.com/package/xpixmap

**Comment by sidorares** [comment]
Hi @klepthys , saw that, nice!
I'm happy to point to your library from readme, but I don't see as part of node-x11 - the intention if this library is to be close to x11 wire protocol ( similar request names, parameters and functionality etc ), not to xlib or xcb. If you want, we could have an example using your lib in `/examples` with its own package.json pointing to npm xpixmap

**Comment by klepthys** [comment]
OK. that's what I thought, and why I made my own module and not propose a PR but I wanted to ask just to be sure I wasn't unnecessarily duplicating work.

I'd like to improve the code further, then I will propose a PR with an example image and a copy of the lib as done in the other examples.

I'll come back to you when it's ready.
